apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJlRENDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzT0RReE16UTJOell3SGhjTk1qWXdOekUxTVRZMU56VTJXaGNOTXpZd056RXlNVFkxTnpVMgpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzT0RReE16UTJOell3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFUblk0UWRCdEZ6Q0w0OEVZd25zaXNVMUR3YXFFZ1ptUzJybUdZN005aE8KMDYvRWc3V2JxRVg2V2xQS2w5YllOVlNZQ1FIYWdZcW5ia0NPa0dlcHVnYU1vMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVUI2TXNJVS9KTkkxeGdFWlpKd25qCklpUXdIdHN3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQU1sOTdwNDE4cUdkUjF5UHYvZ1dLVVN0ekloNjIvcGIKOHlRS2ZhTjArUmZiQWlFQXZ2Ykt5a1lDUlkxeHNwY3JHOVAvWURSSzVpN3BFeWg3dU9HbSsvdXpjbFE9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://127.0.0.1:16443
  name: default
- cluster:
    certificate-authority: /home/devops/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Thu, 16 Jul 2026 15:44:02 PKT
        provider: minikube.sigs.k8s.io
        version: v1.38.1
      name: cluster_info
    server: https://172.16.0.2:8443
  name: dev-cluster
contexts:
- context:
    cluster: default
    user: default
  name: default
- context:
    cluster: dev-cluster
    extensions:
    - extension:
        last-update: Thu, 16 Jul 2026 15:44:02 PKT
        provider: minikube.sigs.k8s.io
        version: v1.38.1
      name: context_info
    namespace: default
    user: dev-cluster
  name: dev-cluster
current-context: dev-cluster
kind: Config
users:
- name: default
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrakNDQVRlZ0F3SUJBZ0lJRHpyM2ZLNFN3TzB3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOemcwTVRNME5qYzJNQjRYRFRJMk1EY3hOVEUyTlRjMU5sb1hEVEkzTURjeApOVEUyTlRjMU5sb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJIbmV4ZlJUaEpsN1V5ZTYKUXBqRkxzVXExMERXZjhWT3dQRWRjNk9nMUFpWENmUHlQTm5xLzl1dXJCOW1TTG12eloyK3NiL2lhMitCNXdTbApYTUVyUjgralNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCUkxqbVQrZWk4VW5uSk1ScmVTWlVYeDZYSDlxakFLQmdncWhrak9QUVFEQWdOSkFEQkcKQWlFQXJrUTEwSUJiMWlwamg4N0lBT2NIclZGMjlyMFFBSitncHJXVEg1d0pXYzhDSVFDRVNKbnZQMEUrUHJiNwpUVWJIZG9QL0pjRmI2MFpBZ3p3dVlyTHZlY29KRnc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCZGpDQ0FSMmdBd0lCQWdJQkFEQUtCZ2dxaGtqT1BRUURBakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwClpXNTBMV05oUURFM09EUXhNelEyTnpZd0hoY05Nall3TnpFMU1UWTFOelUyV2hjTk16WXdOekV5TVRZMU56VTIKV2pBak1TRXdId1lEVlFRRERCaHJNM010WTJ4cFpXNTBMV05oUURFM09EUXhNelEyTnpZd1dUQVRCZ2NxaGtqTwpQUUlCQmdncWhrak9QUU1CQndOQ0FBUkFzUHozQjFiNlJRWjB5L2V5SlVnOGErcDRjejZhdmZYblhwNmhZbGxzCnJVUCtYb0VybG9NaGhHcGVzVEtXMGJYa25zc2phRkpXT21tTWpWRGhGclAybzBJd1FEQU9CZ05WSFE4QkFmOEUKQkFNQ0FxUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVTNDVrL25vdkZKNXlURWEza21WRgo4ZWx4L2Fvd0NnWUlLb1pJemowRUF3SURSd0F3UkFJZ0loL0dDd0ltTEM5Wlc3TlhFdHl2OVFqTXN4cjRJd29sCjI1aUlSdmlXc2xBQ0lGUmJIeVE1dFd3YzlLWUJ4bjM1ejJDdTlYOGdVTFJuK0QyR0VMVndBdTFFCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUVSVkV6clZJM3Noa1ZMMGxxNlpmbE9yZ3hOUFBybEllenNtV2xxWmpFSi9vQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFZWQ3RjlGT0VtWHRUSjdwQ21NVXV4U3JYUU5aL3hVN0E4UjF6bzZEVUNKY0o4L0k4MmVyLwoyNjZzSDJaSXVhL05uYjZ4ditKcmI0SG5CS1Zjd1N0SHp3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
- name: dev-cluster
  user:
    client-certificate: /home/devops/.minikube/profiles/dev-cluster/client.crt
    client-key: /home/devops/.minikube/profiles/dev-cluster/client.key
