apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        # Note: Replace this placeholder with your actual DockerHub backend image
        image: dockerahad/jenkins-devops:latest 
        ports:
        - port: 5002
          targetPort: 5000
          nodePort: 30005
        env:
        - name: DB_HOST
          value: "172.17.0.1"
        - name: DB_PORT
          value: "15432"
        - name: DB_USER
          value: "admin"
        # Using the database password we just verified
        - name: DB_PASSWORD
          value: "password123_" 
        - name: DB_NAME
          value: "mydb"
